version: '2'
services:
  app:
    image: rajunavaganesh/node-demo:latest
    environment:
      NODE_ENV: staging
    command: node_modules/.bin/nodemon --exec npm start
    ports:
      - '2000:2000'
    tty: true
    depends_on:
      - mongodb
    volumes:
      - /home/app/node_docker/node_modules
  mongodb:
    image: mongo:3.2.5
    ports:
      - '27017:27017'
